---
- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - "../files/https_app_onboard_vars.yml"
    
  tasks:
  
    - name: Setup provider
      set_fact:
        provider:
          server: "{{ inventory_hostname }}"
          username: "{{ infoblox_username }}"
          password: "{{ infoblox_password }}"
        
    - name: get network reference
      infoblox:
        provider: "{{ provider }}"
        action: "get_network"
        network: "{{ virtual_network }}"
      register: infoblox

    - name: get next available ips
      infoblox:
        provider: "{{ provider }}"
        action: "get_next_available_ip"
        network: "{{ virtual_network }}"
        start_addr: "{{ start_address }}"
        end_addr: "{{ end_address }}" 
      register: infoblox
      
    - name: create rtp for the retrieve ip
      infoblox:
        provider: "{{ provider }}"
        action=get_network
        network=10.1.212.0/24
      register: infoblox
